CREATE TRANSIENT SCHEMA FIRST_DB.COPIED_SCHEMA
CLONE FIRST_DB.PUBLIC;

-- copy across databases
CREATE TRANSIENT SCHEMA FIRST_DB.EXTERNAL_STAGES_COPIED
CLONE MANAGE_DB.EXTERNAL_STAGES;

-- cloning database
CREATE TRANSIENT DATABASE FIRST_DB_COPY
CLONE FIRST_DB;
