-- data always up-to-date
-- compute paid by customer
-- read-only
  
CREATE OR REPLACE DATABASE DATA_S;

CREATE OR REPLACE TABLE ORDERS (
ORDER_ID	VARCHAR(30)
,AMOUNT	NUMBER(38,0)
,PROFIT	NUMBER(38,0)
,QUANTITY	NUMBER(38,0)
,CATEGORY	VARCHAR(30)
,SUBCATEGORY	VARCHAR(30));
  
CREATE OR REPLACE SHARE ORDERS_SHARE;

GRANT USAGE ON DATABASE DATA_S TO SHARE ORDERS_SHARE; 

GRANT USAGE ON SCHEMA DATA_S.PUBLIC TO SHARE ORDERS_SHARE; 

GRANT SELECT ON TABLE DATA_S.PUBLIC.ORDERS TO SHARE ORDERS_SHARE; 

SHOW GRANTS TO SHARE ORDERS_SHARE;

-- add customer account
ALTER SHARE ORDERS_SHARE ADD ACCOUNT=<consumer-account-id>;

--- CREATE DATABASE FROM SHARE
SHOW SHARES;
--copy owner_account

DESC SHARE <owner_account>.ORDERS_SHARE;
-- to see what was shared (database, schema, table)

-- create a database in consumer account using the share
CREATE DATABASE DATA_SHARE_DB FROM SHARE <account_name_producer>.ORDERS_SHARE;

-- create a virtual warehouse and grant usage from accountadmin
CREATE WAREHOUSE READ_WH WITH
WAREHOUSE_SIZE='X-SMALL'
AUTO_SUSPEND = 180
AUTO_RESUME = TRUE
INITIALLY_SUSPENDED = TRUE;

GRANT USAGE ON WAREHOUSE READ_WH TO ROLE PUBLIC;

-- and finally, reader can see shared data
SELECT * FROM  DATA_SHARE_DB.PUBLIC.ORDERS;

