-- connecting to snowflake from tableau
-- steps:
-- from tableau gui - connect to a server -> more... -> pick snowflake -> paste server name -> pick authentication method as 'Username and Password' and fill in
